name: Expo build

on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]

jobs:
  publish:
    name: Publish to Expo
    runs-on: ubuntu-latest
    needs: test

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - uses: expo/expo-github-action@v5
        with:
          expo-version: 3.x
          expo-username: ${{ secrets.EXPO_CLI_USERNAME }}
          expo-token: ${{ secrets.EXPO_CLI_TOKEN }}
      - run: yarn install
      - run: expo publish
