name: Unit test code and publish to Expo

on:
  pull_request:
    branches: [develop, master]
  push:
    branches: [develop, master]

jobs:
  test:
    name: Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Cache deps
        uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ runner.OS }}-node-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.OS }}-build-${{ env.cache-name }}-
            ${{ runner.OS}}-build
            ${{ runner.OS }}-

      - name: Install deps
        run: yarn install

      - name: Test
        run: yarn test

  publish:
    name: Publish to Expo
    runs-on: ubuntu-latest
    needs: test

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - uses: expo/expo-github-action@v5
        with:
          expo-version: 3.x
          expo-username: ${{ secrets.EXPO_CLI_USERNAME }}
          expo-token: ${{ secrets.EXPO_CLI_TOKEN }}
      - run: yarn install
      - run: expo publish
